spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

jwt:
  secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
  expire-length: 3600000

third-party-api:
  payment:
    base-url: https://api.tosspayments.com
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
